'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { RadioStation, CountryStats, GenreStats } from '@/types/radio';
import { RadioAPI } from '@/utils/radioApi';

interface StationDataContextType {
  stationsWithCoords: RadioStation[];
  allStations: RadioStation[];
  countries: CountryStats[];
  genres: GenreStats[];
  loading: boolean;
  error: string | null;
  importStats: {
    totalStations: number;
    stationsWithoutGeo: number;
    stationsGeocoded: number;
    coveragePercentage: number;
  } | null;
  refresh: () => Promise<void>;
}

const StationDataContext = createContext<StationDataContextType | undefined>(undefined);

export function StationDataProvider({ children }: { children: ReactNode }) {
  const [stationsWithCoords, setStationsWithCoords] = useState<RadioStation[]>([]);
  const [allStations, setAllStations] = useState<RadioStation[]>([]); // Same as coords for now
  const [countries, setCountries] = useState<CountryStats[]>([]);
  const [genres, setGenres] = useState<GenreStats[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [importStats, setImportStats] = useState<any>(null);

  const loadStationData = async () => {
    try {
      setLoading(true);
      setError(null);
      
      console.log('🚀 Loading optimized stations from local JSON...');
      
      // Load the optimized JSON file (generated by scripts/optimize-stations.mjs)
      const response = await fetch('/stations.min.json');
      if (!response.ok) {
        throw new Error(`Failed to load stations: ${response.status}`);
      }
      
      const minifiedData = await response.json();
      console.log(`📦 Loaded ${minifiedData.length} stations from cache.`);

      // Hydrate minified data back to full RadioStation objects
      // Key mapping:
      // id -> stationuuid
      // n -> name
      // c -> country
      // b -> bitrate
      // g -> [lat, lng]
      // t -> tags
      // i -> favicon

      // Map to track duplicate coordinates: "lat,lng" -> count
      const coordCounts = new Map<string, number>();
      
      // Increased grid step to ~800m-1km to scatter stations across the city
      // instead of clumping them in the center square
      const GRID_STEP = 0.008; 

      const hydratedStations: RadioStation[] = minifiedData.map((s: any) => {
        const key = `${s.g[0]},${s.g[1]}`;
        const count = coordCounts.get(key) || 0;
        coordCounts.set(key, count + 1);

        let latOffset = 0;
        let lngOffset = 0;

        if (count > 0) {
           // Spiral-like distribution to cover area more naturally
           // Angle based on golden angle to prevent lines
           const angle = count * 2.4; 
           // Radius grows with square root of count to keep uniform density
           const radius = GRID_STEP * Math.sqrt(count);
           
           latOffset = radius * Math.cos(angle);
           lngOffset = radius * Math.sin(angle);
           
           // Add slight organic noise (10-20%) so it doesn't look like a perfect math formula
           latOffset += (Math.random() - 0.5) * (GRID_STEP * 0.2);
           lngOffset += (Math.random() - 0.5) * (GRID_STEP * 0.2);
        }

        return {
          stationuuid: s.id,
          name: s.n,
          url: '',
          url_resolved: '',
          homepage: '',
          favicon: s.i || '', // Hydrate favicon
          tags: s.t,
          country: s.c,
          countrycode: '',
          state: '',
          language: '',
          votes: 0,
          codec: '',
          bitrate: s.b,
          hls: 0,
          lastcheckok: 1,
          lastchecktime: '',
          lastcheckoktime: '',
          lastchangetime: '',
          clicktimestamp: '',
          clickcount: 0,
          clicktrend: 0,
          ssl_error: 0,
          // Apply grid offset instead of random jitter
          geo_lat: s.g[0] + latOffset,
          geo_long: s.g[1] + lngOffset,
          has_extended_info: false,
        };
      });

      setStationsWithCoords(hydratedStations);
      setAllStations(hydratedStations);
      
      setImportStats({
        totalStations: hydratedStations.length,
        stationsWithoutGeo: 0, // All in this file have geo
        stationsGeocoded: hydratedStations.length,
        coveragePercentage: 100
      });

      console.log(`✅ Hydrated ${hydratedStations.length} stations ready for map.`);
      
    } catch (err) {
      console.error('❌ Error loading stations:', err);
      setError('Failed to load radio stations. Check connection.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadStationData();
  }, []);

  const contextValue: StationDataContextType = {
    stationsWithCoords,
    allStations,
    countries,
    genres,
    loading,
    error,
    importStats,
    refresh: loadStationData
  };

  return (
    <StationDataContext.Provider value={contextValue}>
      {children}
    </StationDataContext.Provider>
  );
}

export function useStationData() {
  const context = useContext(StationDataContext);
  if (context === undefined) {
    throw new Error('useStationData must be used within a StationDataProvider');
  }
  return context;
}
